# Generated by Django 5.2.8 on 2026-08-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='tokens_allocated',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tokens_granted_at',
            field=models.DateTimeField(blank=True, help_text='When the current token bucket was last topped up.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tokens_used',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='token_quota',
            field=models.BigIntegerField(default=0, help_text='LLM tokens granted per billing cycle. 0 = not token-metered.'),
        ),
    ]
