# Generated by Django 5.2.8 on 2026-08-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscription_tokens_allocated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(default='free', help_text='Plan type (e.g., free, pro).', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tokens_allocated',
            field=models.IntegerField(default=0, help_text='Tracks remaining token balance.'),
        ),
    ]
