# Generated by Django 5.2.8 on 2026-09-02 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_subscription_plan_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField(default=0, help_text='Current available token balance.')),
                ('lifetime_purchased', models.BigIntegerField(default=0, help_text='Total tokens ever credited (purchases, bonuses, refunds).')),
                ('lifetime_consumed', models.BigIntegerField(default=0, help_text='Total tokens ever debited (AI usage).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Credit Account',
                'verbose_name_plural': 'User Credit Accounts',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('purchase', 'Purchase'), ('deduction', 'Deduction'), ('refund', 'Refund'), ('bonus', 'Bonus'), ('expiry', 'Expiry')], max_length=20)),
                ('amount', models.BigIntegerField(help_text='Positive for credits, negative for debits.')),
                ('balance_after', models.BigIntegerField(help_text='Account balance snapshot after this transaction.')),
                ('description', models.CharField(max_length=255)),
                ('reference_id', models.CharField(blank=True, default='', help_text='Links to Payment.order_id, Document.id, etc.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.usercreditaccount')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['account', '-created_at'], name='payments_cr_account_5c3ca3_idx')],
            },
        ),
    ]
