import os

from django.conf import settings
from django.db import models
from django.utils.text import slugify
import uuid
from pgvector.django import VectorField



class Document(models.Model):
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="documents",
    )
    title = models.CharField(max_length=255)
    file = models.FileField(upload_to="documents/")

    gemini_file_ref = models.CharField(max_length=255, blank=True, null=True, help_text="Stores the unique file reference from Gemini API.")
    original_name = models.CharField(max_length=255)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    # Added a flag to track if RAG processing is done
    is_processed = models.BooleanField(default=False)

    class Meta:
        ordering = ("-uploaded_at",)

    def __str__(self) -> str:
        return f"{self.title} ({self.owner})"

    @property
    def extension(self) -> str:
        # Try getting extension from the file name first
        name = self.file.name
        _, ext = os.path.splitext(name)
        
        # If missing, fall back to the original filename
        if not ext and self.original_name:
            _, ext = os.path.splitext(self.original_name)
            
        return ext.lower().lstrip(".")

    @property
    def is_pdf(self) -> bool:
        return self.extension == "pdf"
    

class DocumentChunk(models.Model):
    document = models.ForeignKey(
        Document,
        on_delete=models.CASCADE,
        related_name="chunks",
    )
    content = models.TextField()
    # gemini-embedding-001 default 768 dimensions — optimal for retrieval
    embedding = VectorField(dimensions=768) 
    chunk_index = models.IntegerField()

    page_number = models.IntegerField(null=True, blank=True)
    coordinates = models.JSONField(null=True, blank=True)

    class Meta:
        ordering = ("chunk_index",)

    def __str__(self):
        return f"Chunk {self.chunk_index} for {self.document.title}"


class DocumentInsights(models.Model):
    STATUS_PENDING = "pending"
    STATUS_PROCESSING = "processing"
    STATUS_COMPLETED = "completed"
    STATUS_FAILED = "failed"
    STATUS_CHOICES = (
        (STATUS_PENDING, "Pending"),
        (STATUS_PROCESSING, "Processing"),
        (STATUS_COMPLETED, "Completed"),
        (STATUS_FAILED, "Failed"),
    )

    document = models.OneToOneField(
        Document,
        on_delete=models.CASCADE,
        related_name="insights",
    )
    summary = models.TextField(blank=True, default="")
    entities = models.JSONField(
        default=dict,
        help_text='Extracted entities, e.g. {"dates": [], "amounts": [], "names": []}',
    )
    suggested_questions = models.JSONField(
        default=list,
        help_text="Suggested follow-up questions generated by AI.",
    )
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=STATUS_PENDING)
    generated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Document insights"

    def __str__(self) -> str:
        return f"Insights<{self.document_id}> {self.status}"


class ChatSession(models.Model):
    document = models.ForeignKey(
        Document,
        on_delete=models.CASCADE,
        related_name="sessions",
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="chat_sessions",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("document", "user")
        ordering = ("-updated_at",)

    def __str__(self) -> str:
        return f"ChatSession<{self.user} · {self.document}>"


class ChatMessage(models.Model):
    ROLE_CHOICES = (
        ("user", "User"),
        ("assistant", "Assistant"),
    )

    session = models.ForeignKey(
        ChatSession,
        on_delete=models.CASCADE,
        related_name="messages",
    )
    role = models.CharField(max_length=16, choices=ROLE_CHOICES)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("created_at",)

    def __str__(self) -> str:
        return f"{self.role}: {self.content[:40]}..."
