# Generated by Django 5.1.6 on 2025-11-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp_user_email_verified_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
