# Generated by Django 5.2.8 on 2026-01-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_2fa_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Designates whether the user has a premium subscription.'),
        ),
    ]
