# Generated by Django 5.2.8 on 2025-11-26 06:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
