# Generated by Django 5.2.8 on 2025-12-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_content',
            field=models.BinaryField(null=True),
        ),
    ]
