# Generated by Django 5.2.8 on 2026-01-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_file_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_content',
        ),
        migrations.AddField(
            model_name='document',
            name='gemini_file_name',
            field=models.CharField(blank=True, help_text='The internal file name on Google Gemini (e.g., files/12345)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='gemini_file_uri',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
