# Generated by Django 5.2.8 on 2026-01-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_document_file_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='gemini_file_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='gemini_file_uri',
        ),
        migrations.AddField(
            model_name='document',
            name='file_content',
            field=models.BinaryField(null=True),
        ),
    ]
