# Generated by Django 5.2.8 on 2026-01-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_document_gemini_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='gemini_file_ref',
            field=models.CharField(blank=True, help_text='Stores the unique file reference from Gemini API.', max_length=255, null=True),
        ),
    ]
