# Generated by Django 5.2.8 on 2026-01-10 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_gemini_file_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_content',
        ),
    ]
