# Generated by Django 5.2.8 on 2026-01-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_documentchunk'),
    ]

    operations = [
    ]
