# Generated by Django 5.2.8 on 2026-01-14 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_delete_documentchunk'),
    ]

    operations = [
    ]
