# Generated by Django 5.2.8 on 2026-01-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_document_is_processed_documentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='editable_text',
            field=models.TextField(blank=True, help_text='Editable plain-text representation of the document.', null=True),
        ),
    ]
