# Generated by Django 5.2.8 on 2026-01-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_document_has_edits_document_last_edited_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='has_edits',
        ),
        migrations.RemoveField(
            model_name='document',
            name='last_edited_at',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='edited_text',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='last_edited_at',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='original_text',
        ),
        migrations.DeleteModel(
            name='DocumentRevision',
        ),
    ]
