# Generated by Django 5.2.8 on 2026-02-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_document_is_collaborative_document_last_edited_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentannotation',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentannotation',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='document',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_collaborative',
        ),
        migrations.RemoveField(
            model_name='document',
            name='last_edited_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='last_edited_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='latex_content',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='page_num',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='ActiveEditor',
        ),
        migrations.DeleteModel(
            name='DocumentAnnotation',
        ),
        migrations.DeleteModel(
            name='DocumentVersion',
        ),
    ]
