# Generated by Django 5.2.8 on 2026-02-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_remove_documentannotation_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
