# Generated by Django 5.2.8 on 2026-03-13 10:19

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_documentinsights_workspace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentinsights',
            name='document',
        ),
        migrations.AlterUniqueTogether(
            name='workspace',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='document',
            name='workspace',
        ),
        migrations.RemoveIndex(
            model_name='documentchunk',
            name='documents_d_documen_1a14ec_idx',
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=3072),
        ),
        migrations.DeleteModel(
            name='DocumentInsights',
        ),
        migrations.DeleteModel(
            name='Workspace',
        ),
    ]
