# Generated by Django 5.2.8 on 2026-05-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_remove_documentinsights_document_and_more'),
    ]

    operations = [
    ]
