from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0022_enable_vector_extension"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentInsights",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("summary", models.TextField(blank=True, default="")),
                (
                    "entities",
                    models.JSONField(
                        default=dict,
                        help_text='Extracted entities, e.g. {"dates": [], "amounts": [], "names": []}',
                    ),
                ),
                (
                    "suggested_questions",
                    models.JSONField(default=list, help_text="Suggested follow-up questions generated by AI."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="documents.document",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Document insights"},
        ),
    ]
