# Generated by Django 5.2.8 on 2026-08-01 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_documentinsights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='editable_text',
        ),
    ]
