# Generated by Django 5.2.8 on 2026-09-02 11:04

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_remove_document_editable_text'),
    ]

    operations = [
        # Step 1: Delete all existing chunks (they have 3072-dim embeddings
        # and must be re-embedded with 768-dim via `manage.py reembed_documents`)
        migrations.RunSQL(
            sql="DELETE FROM documents_documentchunk;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 2: Reset is_processed flag so documents get re-processed
        migrations.RunSQL(
            sql="UPDATE documents_document SET is_processed = false;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 3: Now safe to alter the column dimensions
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768),
        ),
    ]
